# Generated by Django 4.1 on 2022-10-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='media/pictures/no-img.jpg', upload_to='media/pictures/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='media/files/')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sex', to='creator.sex')),
            ],
        ),
    ]
