# Generated by Django 4.1 on 2022-10-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
