# Generated by Django 4.1 on 2022-10-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_resume_resumeskill_resumeexperience_resumeeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeexperience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeexperience',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
